# Generated by Django 4.0.10 on 2023-09-17 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gamedate', models.DateField(verbose_name='날짜')),
                ('part', models.CharField(max_length=1000000000)),
                ('gamememo', models.CharField(max_length=20, verbose_name='메모')),
                ('coupon', models.IntegerField()),
                ('names', models.CharField(max_length=1000000000)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'v_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gamelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateField(verbose_name='날짜')),
                ('gamememo', models.CharField(max_length=20, verbose_name='메모')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20, unique=True, verbose_name='파트')),
            ],
        ),
        migrations.CreateModel(
            name='Rankname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20, unique=True, verbose_name='순위')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='쿠폰')),
                ('foreignkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliers_Score_foreignkey', to='pyhome.gamelist', verbose_name='foreignkey')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliers_Score_rank', to='pyhome.rankname', verbose_name='순위')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliers_Score_username', to=settings.AUTH_USER_MODEL, verbose_name='이름')),
            ],
        ),
        migrations.AddField(
            model_name='gamelist',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliers_part', to='pyhome.part', verbose_name='파트'),
        ),
    ]
